
name: react-test-pr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: ./src/ReactAccessibilityTesting/ReactAccessibilityTesting
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        # cache: 'npm'
    - name: npm install
      working-directory: ./src/ReactAccessibilityTesting/ReactAccessibilityTesting
      run: npm ci
    - name: npm build
      run: npm run build --if-present
    - name: npm tests
      run: npm test