
name: react-test-pr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      working-directory: ./src/ReactAccessibilityTesting/ReactAccessibilityTesting
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: npm install
      working-directory: ./src/ReactAccessibilityTesting/ReactAccessibilityTesting
      run: npm ci
    - name: npm build
      working-directory: ./src/ReactAccessibilityTesting/ReactAccessibilityTesting
      run: npm run build --if-present
    - name: npm tests
      working-directory: ./src/ReactAccessibilityTesting/ReactAccessibilityTesting
      run: npm test